server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
spring:
  datasource:
    password: password
    url: jdbc:postgresql://localhost:5432/skillbox?stringtype=unspecified
    username: skillbox
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true
  sql:
    init:
      mode: always
